services:
  pygeoapi:
    container_name: pygeoapi
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      tags:
        - pygeoapi:latest
        - ${AWS_ECR_TAG}
    platform: linux/amd64
    ports:
      - "${PYGEOAPI_PORT}:${PYGEOAPI_PORT}"
    env_file:
      - .env-default
      - .env
    restart: unless-stopped
